baseURL = 'https://ziminds.com/'
languageCode = 'en-us'
title = 'De Omnibus Dubitandum'
theme = 'PaperMod'

[params.homeInfoParams]
Title = "Hi there 👋"
Content = "My name is Zimin, and I talk about #tech, #art, and random things"

[[params.socialIcons]]
name = "github"
url = "https://github.com/21m1n"

[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/zi-min/"


[outputs]
home = [ "HTML", "RSS", "JSON" ]

[params.assets]
disableHLJS = true

[markup]
  [markup.highlight]
    style = "dracula"
    lineNos = false
    noClasses = true
    codeFences = true

[params]
ShowPostNavLinks = true
ShowToc = true
TocOpen = true
ShowBreadCrumbs = true
ShowReadingTime = true
ShowShareButtons = true
ShowWordCount = true
comments = true
searchHidden = false