baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'De Onmibus Dubitaddum'
theme = 'PaperMod'

[params.homeInfoParams]
Title = "Hi there 👋"
Content = "My name is Zimin, and I talk about #tech, #films, #life"

[[params.socialIcons]]
name = "<platform>"
url = "<link>"

[[params.socialIcons]]
name = "<platform 2>"
url = "<link2>"

[outputs]
home = [ "HTML", "RSS", "JSON" ]
