baseURL = 'https://ziminds.com/'
languageCode = 'en-us'
title = 'De Omnibus Dubitandum'
theme = 'PaperMod'

[params.homeInfoParams]
Title = "Hi there 👋"
Content = "My name is Zimin, and I talk about #tech, #art, and random things"

[[params.socialIcons]]
name = "<platform>"
url = "<link>"

[[params.socialIcons]]
name = "<platform 2>"
url = "<link2>"

[outputs]
home = [ "HTML", "RSS", "JSON" ]
