name: Deploy Hugo site to Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.88.1'

      - name: Build
        run: hugo --minify

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: site
          path: public